# Generated by Django 5.0 on 2023-12-07 18:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="user_id",
            field=models.CharField(
                default=uuid.uuid4,
                max_length=36,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
