# Generated by Django 5.0 on 2023-12-07 18:57

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0002_alter_appuser_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "reference_id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_on", models.DateField(blank=True, null=True)),
                ("name", models.CharField(max_length=30)),
                ("location", models.CharField(max_length=50)),
                ("is_full", models.BooleanField()),
                ("description", models.TextField(blank=True, max_length=1000)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=datetime.datetime.now,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "reference_id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_on", models.DateField(blank=True, null=True)),
                ("rating", models.IntegerField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=datetime.datetime.now,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="base_app.hotel"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
