# Generated by Django 5.0 on 2023-12-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0006_hotel_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="description_image",
            field=models.ImageField(blank=True, upload_to="uploads/"),
        ),
    ]
