# Generated by Django 5.0 on 2023-12-07 19:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0003_hotel_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hotel",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="hotel",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="review",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="review",
            name="created_on",
        ),
        migrations.AlterField(
            model_name="review",
            name="hotel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reviews",
                to="base_app.hotel",
            ),
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "reference_id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("booked_on", models.DateField()),
                ("checked_out_on", models.DateField()),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="booking_reviews",
                        to="base_app.hotel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
