# Generated by Django 5.0 on 2023-12-07 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0004_remove_hotel_created_by_remove_hotel_created_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="hotel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="base_app.hotel",
            ),
        ),
    ]
