# Generated by Django 5.0 on 2023-12-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0005_alter_booking_hotel"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="rating",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
